[phases.setup]
# Especificamos las versiones de software. PHP 8.1 es compatible con tu proyecto.
nixPkgs = ["...", "php81", "composer", "nodejs-16_x", "yarn"]

# Comandos de configuración para instalar las extensiones de PHP.
cmds = [
  "sudo pecl install pdo_sqlsrv",
  "sudo pecl install sqlsrv",
  "sudo bash -c 'echo \"extension=pdo_sqlsrv.so\" >> /etc/php/8.1/cli/php.ini'",
  "sudo bash -c 'echo \"extension=sqlsrv.so\" >> /etc/php/8.1/cli/php.ini'",
  "sudo apt-get update", # Actualizamos los repositorios del sistema operativo
  "sudo apt-get install -y ffmpeg" # Instalamos FFmpeg para el paquete php-ffmpeg
]

[phases.build]
# Comandos de construcción de PHP y Node.js.
cmds = ["composer install --no-dev", "npm install && npm run production"]

[start]
# Comando para iniciar la aplicación.
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[variables]
# Configuración adicional si es necesario.
# Por ejemplo, la ruta de LibreOffice puede ser diferente en Linux.
# En Railway, deberías instalar LibreOffice y luego configurar esta variable.
# Esto es solo un ejemplo, la instalación de LibreOffice es más compleja.
# LIBREOFFICE_PATH = "/usr/bin/libreoffice"