[phases.setup]
# Especificamos las herramientas necesarias.
# Usamos 'phpPackages.composer' y 'nodejs' para la sintaxis correcta en Nix.
nixPkgs = [
  "php81",
  "phpPackages.composer",
  "nodejs",
  "yarn",
  "ffmpeg",
  "libmysqlclient" # Opcional: si necesitas la extensi贸n de MySQL/MariaDB
]

# Comandos de instalaci贸n de extensiones de PHP para SQL Server.
cmds = [
  "sudo pecl install pdo_sqlsrv",
  "sudo pecl install sqlsrv",
  "sudo bash -c 'echo \"extension=pdo_sqlsrv.so\" >> /etc/php/8.1/cli/php.ini'",
  "sudo bash -c 'echo \"extension=sqlsrv.so\" >> /etc/php/8.1/cli/php.ini'"
]

[phases.build]
# Comandos de construcci贸n para PHP y Node.js.
cmds = ["composer install --no-dev", "npm install && npm run production"]

[start]
# Comando para iniciar el servidor de Laravel.
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[variables]
# Configuraci贸n para optimizar el funcionamiento de Nix en Railway.
NIX_CONFIG = "extra-substituters = https://cache.nixos.org https://nix-community.cachix.org?priority=10\nextra-trusted-public-keys = cache.nixos.org-1:6NCHd/XgW5ueb72bwKaQxKqClyObeWaAIyS1pA/pUqM= nix-community.cachix.org-1:m3h32y1J7gNf+P1Q/fA97Fh8tL7J8nB4s6d65w5e/zY="