# nixpacks.toml

# Configuración de las fases de construcción
[phases.setup]
# Usamos NixPkgs para especificar las herramientas necesarias.
nixPkgs = ["...", "php", "composer", "nodejs", "yarn"]

# La lista de comandos debe estar directamente bajo [phases.setup]
# No se debe usar un subencabezado [phases.setup.cmds]
cmds = [
  "sudo pecl install pdo_sqlsrv",
  "sudo pecl install sqlsrv",
  "sudo bash -c 'echo \"extension=pdo_sqlsrv.so\" >> /etc/php/7.4/cli/php.ini'",
  "sudo bash -c 'echo \"extension=sqlsrv.so\" >> /etc/php/7.4/cli/php.ini'"
]

# Configuración de los comandos de inicio
[start]
# El comando para iniciar la aplicación Laravel.
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

# Configuración de la fase de construcción
[phases.build]
cmds = ["composer install --no-dev", "npm install && npm run build"]