[phases.setup]
# Lista de paquetes necesarios, incluyendo PHP, Node.js, etc.
nixPkgs = [
  "php81",
  "phpPackages.composer",
  "nodejs",
  "yarn",
  "ffmpeg",
  "libmysqlclient" # Opcional: si lo necesitas
]

# Comandos para instalar el driver ODBC y otras dependencias del sistema.
# El orden es importante: primero las dependencias, luego las extensiones de PHP.
cmds = [
  # Instalación del driver ODBC para SQL Server
  "curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -",
  "curl https://packages.microsoft.com/config/debian/11/prod.list | sudo tee /etc/apt/sources.list.d/mssql-tools.list",
  "sudo apt-get update",
  "sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev",

  # Instalación de las extensiones de PHP
  "sudo pecl install pdo_sqlsrv",
  "sudo pecl install sqlsrv",
  "sudo bash -c 'echo \"extension=pdo_sqlsrv.so\" >> /etc/php/8.1/cli/php.ini'",
  "sudo bash -c 'echo \"extension=sqlsrv.so\" >> /etc/php/8.1/cli/php.ini'"
]

[phases.build]
cmds = ["composer install --no-dev", "npm install && npm run production"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[variables]
NIX_CONFIG = "extra-substituters = https://cache.nixos.org https://nix-community.cachix.org?priority=10\nextra-trusted-public-keys = cache.nixos.org-1:6NCHd/XgW5ueb72bwKaQxKqClyObeWaAIyS1pA/pUqM= nix-community.cachix.org-1:m3h32y1J7gNf+P1Q/fA97Fh8tL7J8nB4s6d65w5e/zY="